print ("What is your name?",end=" ")
name=input()
print ("How old are you?",end=" ")
age=input()
print ("How much do you weigh?",end=" ")
weight=input()
print ("What is your height?",end=" ")
height=input()

print ("So %r ,you are %r years old ,weigh %r and %r tall" %(name,age,weight,height))